//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_005_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_005_ESTADO()
        {
            this.BS_006_CIDADE = new HashSet<BS_006_CIDADE>();
        }
    
        public int ID_ESTADO { get; set; }
        public string UF { get; set; }
        public string NOME_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_006_CIDADE> BS_006_CIDADE { get; set; }
    }
}
