//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_008_ESTUDANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_008_ESTUDANTE()
        {
            this.BS_001_CURSO = new HashSet<BS_001_CURSO>();
        }
    
        public int ID_ESTUDANTE { get; set; }
        public string NOME_ESTUDANTE { get; set; }
        public string EMAIL_ESTUDANTE { get; set; }
        public int ID_TELEFONE { get; set; }
        public int ID_ENDERECO { get; set; }
    
        public virtual BS_004_TELEFONE BS_004_TELEFONE { get; set; }
        public virtual BS_007_ENDERECO BS_007_ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_001_CURSO> BS_001_CURSO { get; set; }
    }
}
