//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_001_CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_001_CURSO()
        {
            this.BS_002_PROFESSOR = new HashSet<BS_002_PROFESSOR>();
            this.BS_008_ESTUDANTE = new HashSet<BS_008_ESTUDANTE>();
        }
    
        public int ID_CURSO { get; set; }
        public string NOME_CURSO { get; set; }
        public string DESCRICAO_CURSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_002_PROFESSOR> BS_002_PROFESSOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_008_ESTUDANTE> BS_008_ESTUDANTE { get; set; }
    }
}
