//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_006_CIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_006_CIDADE()
        {
            this.BS_007_ENDERECO = new HashSet<BS_007_ENDERECO>();
        }
    
        public int ID_CIDADE { get; set; }
        public int ID_ESTADO { get; set; }
        public string NOME_CIDADE { get; set; }
    
        public virtual BS_005_ESTADO BS_005_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_007_ENDERECO> BS_007_ENDERECO { get; set; }
    }
}
