//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_004_TELEFONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_004_TELEFONE()
        {
            this.BS_008_ESTUDANTE = new HashSet<BS_008_ESTUDANTE>();
        }
    
        public int ID_TELEFONE { get; set; }
        public int DDD_TELEFONE { get; set; }
        public int TELEFONE { get; set; }
        public int DDD_CELULAR { get; set; }
        public int CELULAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_008_ESTUDANTE> BS_008_ESTUDANTE { get; set; }
    }
}
