//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_000_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string NOME_USUARIO { get; set; }
        public int ID_PERFIL { get; set; }
    
        public virtual BS_010_PERFIL BS_010_PERFIL { get; set; }
    }
}
