//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_007_ENDERECO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_007_ENDERECO()
        {
            this.BS_008_ESTUDANTE = new HashSet<BS_008_ESTUDANTE>();
        }
    
        public int ID_ENDERECO { get; set; }
        public string NOME_ENDERECO { get; set; }
        public int CEP_ENDERECO { get; set; }
        public string BAIRRO_ENDERECO { get; set; }
        public string LOTE_ENDERECO { get; set; }
        public int ID_CIDADE { get; set; }
    
        public virtual BS_006_CIDADE BS_006_CIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_008_ESTUDANTE> BS_008_ESTUDANTE { get; set; }
    }
}
