//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_002_PROFESSOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_002_PROFESSOR()
        {
            this.BS_001_CURSO = new HashSet<BS_001_CURSO>();
        }
    
        public int ID_PROFESSOR { get; set; }
        public string NOME_PROFESSOR { get; set; }
        public string SOBRENOME_PROFESSOR { get; set; }
        public string EMAIL_PROFESSOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_001_CURSO> BS_001_CURSO { get; set; }
    }
}
