//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumoATI.ETB.Domain.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BRINCANDO_SQLEntities : DbContext
    {
        public BRINCANDO_SQLEntities()
            : base("name=BRINCANDO_SQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BS_000_USUARIO> BS_000_USUARIO { get; set; }
        public virtual DbSet<BS_001_CURSO> BS_001_CURSO { get; set; }
        public virtual DbSet<BS_002_PROFESSOR> BS_002_PROFESSOR { get; set; }
        public virtual DbSet<BS_004_TELEFONE> BS_004_TELEFONE { get; set; }
        public virtual DbSet<BS_005_ESTADO> BS_005_ESTADO { get; set; }
        public virtual DbSet<BS_006_CIDADE> BS_006_CIDADE { get; set; }
        public virtual DbSet<BS_007_ENDERECO> BS_007_ENDERECO { get; set; }
        public virtual DbSet<BS_008_ESTUDANTE> BS_008_ESTUDANTE { get; set; }
        public virtual DbSet<BS_010_PERFIL> BS_010_PERFIL { get; set; }
    }
}
