// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RumoATI.ETB.Domain2.Context;

namespace RumoATI.ETB.Domain2.Migrations
{
    [DbContext(typeof(ETBContext))]
    partial class ETBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RumoATI.ETB.Domain2.Entidades.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("BS_010_PERFIL");
                });

            modelBuilder.Entity("RumoATI.ETB.Domain2.Entidades.Professor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID_PROFESSOR");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL_PROFESSOR");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME_PROFESSOR");

                    b.Property<string>("SobreNome")
                        .HasColumnName("SOBRENOME_PROFESSOR");

                    b.HasKey("Id");

                    b.ToTable("BS_002_PROFESSOR");
                });

            modelBuilder.Entity("RumoATI.ETB.Domain2.Entidades.ProfessorCurso", b =>
                {
                    b.Property<int>("IdCurso")
                        .HasColumnName("ID_CURSO");

                    b.Property<int>("IdProfessor")
                        .HasColumnName("ID_PROFESSOR");

                    b.HasKey("IdCurso", "IdProfessor");

                    b.HasIndex("IdProfessor");

                    b.ToTable("BS_003_PROFESSOR_CURSO");
                });

            modelBuilder.Entity("RumoATI.ETB.Domain2.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_USUARIO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPerfil")
                        .HasColumnName("ID_PERFIL");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.ToTable("BS_000_USUARIO");
                });

            modelBuilder.Entity("umoATI.ETB.Domain2.Entidades.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CURSO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("DESCRICAO_CURSO");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME_CURSO");

                    b.HasKey("Id");

                    b.ToTable("BS_001_CURSO");
                });

            modelBuilder.Entity("RumoATI.ETB.Domain2.Entidades.Professor", b =>
                {
                    b.HasOne("RumoATI.ETB.Domain2.Entidades.Usuario", "Usuario")
                        .WithOne("Professor")
                        .HasForeignKey("RumoATI.ETB.Domain2.Entidades.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RumoATI.ETB.Domain2.Entidades.ProfessorCurso", b =>
                {
                    b.HasOne("umoATI.ETB.Domain2.Entidades.Curso", "Curso")
                        .WithMany("ProfessoresCurso")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RumoATI.ETB.Domain2.Entidades.Professor", "Professor")
                        .WithMany("ProfessoresCurso")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RumoATI.ETB.Domain2.Entidades.Usuario", b =>
                {
                    b.HasOne("RumoATI.ETB.Domain2.Entidades.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
